version: 2.1

executors:
  default-executor:
    docker:
      - image: cypress/base:10

jobs:
  install-dependencies:
    executor: default-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-deps-{{ checksum "package-lock.json" }}
            - v2-deps

      - run:
          name: 'Install dependencies'
          command: npm ci

      - save_cache:
          paths:
            - ~/.npm
            - ~/.cache
          key: v2-deps-{{ checksum "package-lock.json" }}

      - persist_to_workspace:
          root: .
          paths: .

  check-prettier:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Run prettier check on project files'
          command: npm run prettier:check

  check-linter:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Run linter'
          command: npm run lint

  run-unit-tests:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Run unit tests'
          command: npm run test:unit

  run-e2e-tests:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v2-deps-{{ checksum "package-lock.json" }}
            - v2-deps
      - run:
          name: 'Run e2e tests'
          command: npm run test:e2e:headless

  build:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Build'
          command: npm run build
      - persist_to_workspace:
          root: .
          paths: .

  check-bundles-sizes:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Check bundles sizes'
          command: npm run bundlesize

  deploy:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Firebase deploy'
          command: |
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then
              npm run firebase:deploy:ci
            fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install-dependencies
      - check-prettier:
          requires:
            - install-dependencies
      - check-linter:
          requires:
            - install-dependencies
      - run-unit-tests:
          requires:
            - install-dependencies
      - run-e2e-tests:
          requires:
            - install-dependencies
      - build:
          requires:
            - check-prettier
            - check-linter
            - run-unit-tests
            - run-e2e-tests
      - check-bundles-sizes:
          requires:
            - build
      - deploy:
          requires:
            - check-bundles-sizes