version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8-browsers

    working_directory: ~/vue-ts-firebase-starter

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies

      - run:
          name: 'Install dependencies'
          command: yarn

      - save_cache:
          paths:
            - ~/.cache
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: 'Run prettier check on project files'
          command: yarn prettier:check

      - run:
          name: 'Run linter'
          command: yarn lint

      - run:
          name: 'Run unit tests'
          command: yarn test:unit

      - run:
          name: 'Run e2e tests'
          command: yarn test:e2e:headless

      - run:
          name: 'Run lighthouse audit'
          command: 'yarn audit'

      - run:
          name: 'Build'
          command: yarn build

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
