version: 2
jobs:
  build:
    docker:
      - image: imton/cypress-chrome71

    working_directory: ~/vue-ts-firebase-starter

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies

      - run:
          name: 'Install dependencies'
          command: npm i

      - save_cache:
          paths:
            - ~/.cache
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: 'Run prettier check on project files'
          command: npm run prettier:check

      - run:
          name: 'Run linter'
          command: npm run lint

      - run:
          name: 'Run unit tests'
          command: npm run test:unit

      - run:
          name: 'Run e2e tests'
          command: npm run test:e2e:headless

      - run:
          name: 'Build'
          command: npm run build

      - run:
          name: 'Check bundles sizes'
          command: npm run bundlesize

      - run:
          name: 'Firebase deploy'
          command: |
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then
              npm run firebase:deploy
            fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
