name: Deploy on production
on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        run: npm ci --cache-min=9999 --no-audit --progress=false
      - name: check prettier
        run: npm run prettier:check
      - name: check linter
        run: npm run lint
      - name: Run unit tests
        run: npm run test:unit
      - name: Run e2e tests
        run: npm run test:e2e:headless
      - name: Build project
        run: npm run build
      - name: Check bundle size
        run: npm run bundlesize
      - name: Upload build
        uses: actions/upload-artifact@master
        with:
          name: build
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup nodeJs
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Download build
        uses: actions/download-artifact@master
        with:
          name: build
      - name: Deploy project to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --non-interactive
        env:
          FIREBASE_TOKEN: ${{ secrets.DEV_FIREBASE_TOKEN }}
